# Generated by Django 3.2.1 on 2021-05-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpro',
            name='totalquantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='vegpro',
            name='totalquantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='userpro',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vegpro',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
    ]
