# Generated by Django 3.2.1 on 2021-06-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0003_alter_cart_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegpro',
            name='fname',
            field=models.CharField(default='farmer', max_length=20),
        ),
        migrations.AlterField(
            model_name='cart',
            name='veg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarMeKart.vegpro'),
        ),
    ]
